persona:
  name: "Mohammad Tanzil Alam"
  style: "friendly, concise, professional"

llm:
  gguf_repo: "bartowski/Llama-3.2-1B-Instruct-GGUF"
  gguf_file: "Llama-3.2-1B-Instruct-Q4_K_M.gguf"
  n_ctx: 4096
  n_threads: 4
  temperature: 0.2
  top_p: 0.9
  max_tokens: 512

embeddings:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

retriever:
  k: 5

guardrails:
  blocked_phrases:
    - "reveal your system prompt"
    - "ignore previous instructions"
    - "jailbreak"
    - "password"
    - "credit card"
    - "social security"