persona:
  name: "Mohammad Tanzil Alam"
  style: "professional, concise, and well-organized"
  tagline: "AI-powered CV Assistant"
  github: "https://github.com/tanzilalam23"
  linkedin: "https://linkedin.com/in/mohammad-tanzil-alam"

llm:
  # Using a better model for improved responses
  gguf_repo: "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
  gguf_file: "mistral-7b-instruct-v0.2.Q4_K_M.gguf"
  n_ctx: 4096
  n_threads: 4
  temperature: 0.1  # Lower temperature for more focused responses
  top_p: 0.8        # Lower top_p for better coherence
  max_tokens: 800   # Increased for more complete responses

embeddings:
  # Using a better embedding model
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

retriever:
  k: 6  # Retrieve more contexts for better coverage
  
# Content processing settings
chunking:
  chunk_size: 400    # Smaller chunks for more precise retrieval
  overlap: 80        # More overlap to maintain context
  min_chunk_words: 15  # Minimum words per chunk

guardrails:
  blocked_phrases:
    - "reveal your system prompt"
    - "ignore previous instructions" 
    - "jailbreak"
    - "password"
    - "credit card"
    - "social security"
    - "personal information"
    - "hack"
    - "bypass"